"""Phase-response (and skew) measurement with the dither generated inside a
720-point block FFT in the TX DSP.

Constraint: the TX frequency-domain processing is a 720-point FFT per block
(720 samples at 200 GS/s = 3.6 ns, bin spacing 277.8 MHz).  The dither is
therefore implemented as

    for each block b:  X_b[k] *= 1 + eps * cos(2*pi*nu*t_b)   for k in slice

i.e. one scalar gain per block applied to the bins of the dithered slice
(nu = 90 MHz is below the bin spacing, so this is the "block-level gain"
form; the cos is zero-order-held at the block rate, t_b = block centre).
The NCO phase is global (never reset), the ADC lock-in uses the same
global time, so records add coherently.

Scenario: common quadratic phase -6 (f/50 GHz)^2 rad on I and Q,
I/Q skew 0.3 ps, |H_I| != |H_Q|.  PD 100 MHz, ADC 200 MS/s, nu = 90 MHz.

Contiguous slices of 18 bins (5 GHz) from 0 to 50 GHz; per slice and per
branch the lock-in phase gives the slice-average group delay
    tau_g(k) = (arg M(nu) - arg B(k)) / (2 pi nu)
and the phase is accumulated slice by slice (telescoping):
    theta(f_{k+1}) = theta(f_k) - 2 pi Delta tau_g(k).

Usage: python phase_sweep_fft720.py --eps-slice 0.8 --t-slice-ms 10 --procs 4
       python phase_sweep_fft720.py --replot --out <name>
"""
import argparse
import os
import sys
import time
from multiprocessing import Pool

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from s21_monitor import make_transmitter, lowpass_fir, rrc_fir
from s21_monitor.filters import causal_conv, fft_conv_full
from s21_monitor.transmitter import WidelyLinearTransmitter

# ----------------------------------------------------------------------------
fs = 200e9
BLK = 720                       # TX FFT size
NB = 300                        # blocks per simulated record
N = BLK * NB                    # 216000 samples = 1.08 us
D_adc = 1000                    # -> 200 MS/s
fs_adc = fs / D_adc
Nd = N // D_adc                 # 216 ADC samples per record
T_rec = N / fs
nu = 90e6
bin_tx = fs / BLK               # 277.78 MHz
NBIN_SLICE = 18                 # 5 GHz per slice
K = 10                          # 0 .. 50 GHz
Delta = NBIN_SLICE * bin_tx
edges = np.arange(K + 1) * Delta

SKEW_PS = 0.3
QUAD_RAD, F_EDGE = 6.0, 50e9
snr_db_adc = 30.0

# transmitter: common quadratic phase + 0.3 ps skew, different |H|
_nap = 8192
_fap = np.fft.rfftfreq(_nap, 1 / fs)
_ap = np.fft.irfft(np.exp(-1j * QUAD_RAD * (_fap / F_EDGE) ** 2), _nap)
_ap = np.roll(_ap, 200)[:401] * np.hamming(401)
_tx0 = make_transmitter(branch_taps=41, bw_i=0.55, bw_q=0.50,
                        gain_q=10 ** (-0.8 / 20), phase_error_deg=0.0,
                        skew_samples=SKEW_PS * 1e-12 * fs, delay_taps=15)
_L = np.zeros((2, 2, _tx0.L.shape[2] + 400))
for _i in range(2):
    for _j in range(2):
        _L[_i, _j] = fft_conv_full(_tx0.L[_i, _j], _ap)
tx = WidelyLinearTransmitter(_L)
hI, hQ = tx.L[0, 0], tx.L[1, 1]
M_true = lowpass_fir(8001, 100e6 / (fs / 2))

freqs = np.fft.rfftfreq(N, 1 / fs)
HII = np.fft.rfft(hI, N)
HQQ = np.fft.rfft(hQ, N)
M_f = np.fft.rfft(M_true, N)
M_nu = np.interp(nu, freqs, M_f.real) + 1j * np.interp(nu, freqs, M_f.imag)

rrc = rrc_fir(65, 0.1, 2)
levels = np.array([-3.0, -1.0, 1.0, 3.0])
S_rrc = np.abs(np.fft.rfft(rrc, N)) ** 2
w_adc = np.hanning(Nd)
n_adc = np.arange(Nd)
t_blk = (np.arange(NB) * BLK + (BLK - 1) / 2) / fs   # block centres (sample n is at n/fs)
bin_masks = [np.zeros(BLK // 2 + 1, bool) for _ in range(K)]
for k in range(K):
    bin_masks[k][k * NBIN_SLICE:(k + 1) * NBIN_SLICE] = True
zoh = np.sinc(nu / bin_tx)                          # ZOH fundamental gain


def make_data(rng):
    out = []
    for _ in range(2):
        up = np.zeros(N)
        up[::2] = rng.choice(levels, N // 2)
        x = causal_conv(rrc, up)
        out.append(x / np.std(x))
    return out


def tx_dither_720(x, mask, eps, t0):
    """Dither perturbation generated by the 720-point block FFT.

    Bins in `mask` of block b are multiplied by 1 + eps*cos(2 pi nu t_b);
    the returned d is the difference to the undithered stream.
    """
    xb = x.reshape(NB, BLK)
    Xb = np.fft.rfft(xb, axis=1)
    g = eps * np.cos(2 * np.pi * nu * (t0 + t_blk))
    Db = Xb * mask[None, :] * g[:, None]
    return np.fft.irfft(Db, BLK, axis=1).reshape(N)


def one_record(rng, branch, mask, eps, noise_std, r):
    t0 = r * T_rec
    xI, xQ = make_data(rng)
    x = [xI, xQ]
    d = tx_dither_720(x[branch], mask, eps, t0)
    x[branch] = x[branch] + d
    yI = np.fft.irfft(np.fft.rfft(x[0]) * HII, N)
    yQ = np.fft.irfft(np.fft.rfft(x[1]) * HQQ, N)
    p = yI ** 2 + yQ ** 2
    z = np.fft.irfft(np.fft.rfft(p) * M_f, N)[::D_adc]
    z = z + noise_std * rng.standard_normal(Nd)
    z = z - z.mean()
    lock = w_adc * np.exp(-2j * np.pi * nu * (t0 + n_adc / fs_adc))
    B = np.sum(lock * z)
    spec = np.abs(np.fft.rfft(w_adc * z)) ** 2
    return B, spec


def worker(args):
    seed, start, n_rec, eps, noise_std = args
    rng = np.random.default_rng(seed)
    acc = np.zeros(2 * K, complex)
    cnt = np.zeros(2 * K, int)
    acc2 = np.zeros(2 * K)                     # for a noise estimate
    spec = np.zeros(Nd // 2 + 1)
    for i in range(n_rec):
        r = start + i
        b = r % 2
        k = (r // 2) % K
        B, sp = one_record(rng, b, bin_masks[k], eps, noise_std, r)
        acc[2 * k + b] += B
        acc2[2 * k + b] += abs(B) ** 2
        cnt[2 * k + b] += 1
        spec += sp
    return acc, acc2, cnt, spec


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--eps-slice", type=float, default=0.8)
    ap.add_argument("--t-slice-ms", type=float, default=10.0)
    ap.add_argument("--procs", type=int, default=4)
    ap.add_argument("--out", default="phase_sweep_fft720")
    ap.add_argument("--replot", action="store_true")
    ap.add_argument("--recompute", action="store_true",
                    help="re-derive everything from the stored lock-in outputs")
    ap.add_argument("--legacy-half-sample", action="store_true",
                    help="with --recompute: file was made before the block-centre fix")
    a = ap.parse_args()
    if a.replot:
        make_figure(a.out)
        return
    if a.recompute:
        recompute(a.out, a.legacy_half_sample)
        return

    eps = a.eps_slice
    rng = np.random.default_rng(1)
    xI, xQ = make_data(rng)
    yI = np.fft.irfft(np.fft.rfft(xI) * HII, N)
    yQ = np.fft.irfft(np.fft.rfft(xQ) * HQQ, N)
    z0 = np.fft.irfft(np.fft.rfft(yI ** 2 + yQ ** 2) * M_f, N)[::D_adc]
    noise_std = np.sqrt(np.var(z0) * 10 ** (-snr_db_adc / 10))
    # dither power relative to the data (EVM cost), slice power from the RRC PSD
    p_slice = np.array([np.sum(S_rrc[(freqs >= edges[k]) & (freqs < edges[k + 1])])
                        for k in range(K)])
    frac = eps ** 2 / 2 * p_slice / np.sum(S_rrc)
    print(f"nu={nu / 1e6:.0f} MHz, ADC {fs_adc / 1e6:.0f} MS/s, TX FFT {BLK} "
          f"(bin {bin_tx / 1e6:.1f} MHz), {K} slices x {NBIN_SLICE} bins = {Delta / 1e9:.1f} GHz, "
          f"ZOH gain {zoh:.3f}\n"
          f"eps_slice={eps}: dither power {frac.max() * 100:.2f}% of data "
          f"({10 * np.log10(frac.max()):.1f} dB) in the worst slice; "
          f"EVM-neutral reference (-25 dB) is eps_slice={0.08 * np.sqrt(np.sum(S_rrc) / p_slice.max()):.3f}",
          flush=True)

    n_total = int(round(2 * K * a.t_slice_ms * 1e-3 / T_rec))
    per = (n_total + a.procs - 1) // a.procs
    jobs = [(300 + j, j * per, min(per, n_total - j * per), eps, noise_std)
            for j in range(a.procs)]
    t0 = time.time()
    with Pool(a.procs) as pool:
        outs = pool.map(worker, jobs)
    acc = sum(o[0] for o in outs)
    acc2 = sum(o[1] for o in outs)
    cnt = sum(o[2] for o in outs)
    spec = sum(o[3] for o in outs) / n_total
    print(f"{n_total} records ({n_total * T_rec * 1e3:.1f} ms total, "
          f"{a.t_slice_ms:.1f} ms per slice per branch) in {time.time() - t0:.0f} s", flush=True)

    B = acc / cnt
    # per-record scatter -> standard error of the mean (complex, isotropic)
    var1 = acc2 / cnt - np.abs(B) ** 2
    sem = np.sqrt(var1 / cnt / 2)                   # per quadrature
    B_I, B_Q = B[0::2], B[1::2]
    sig_ph_I = sem[0::2] / np.abs(B_I)
    sig_ph_Q = sem[1::2] / np.abs(B_Q)
    res = analyze(B_I, B_Q, sig_ph_I, sig_ph_Q)
    res.update(spec=spec, eps=eps, t_slice_ms=a.t_slice_ms, frac_db=10 * np.log10(frac.max()),
               B_I=B_I, B_Q=B_Q, sig_ph_I=sig_ph_I, sig_ph_Q=sig_ph_Q)
    np.savez(a.out + ".npz", **res)
    report(res)
    make_figure(a.out)


def _H_shift(Hb):
    """H(f + nu) on the fine grid by complex linear interpolation (nu is not
    an integer number of fine bins for this record length)."""
    return (np.interp(freqs + nu, freqs, Hb.real, right=0.0)
            + 1j * np.interp(freqs + nu, freqs, Hb.imag, right=0.0))


def analyze(B_I, B_Q, sig_ph_I, sig_ph_Q):
    tau_I = (np.angle(M_nu) - np.angle(B_I)) / (2 * np.pi * nu)
    tau_Q = (np.angle(M_nu) - np.angle(B_Q)) / (2 * np.pi * nu)
    sig_tau_I = sig_ph_I / (2 * np.pi * nu)
    sig_tau_Q = sig_ph_Q / (2 * np.pi * nu)
    th_I = -2 * np.pi * np.concatenate(([0.0], np.cumsum(tau_I * Delta)))
    th_Q = -2 * np.pi * np.concatenate(([0.0], np.cumsum(tau_Q * Delta)))
    sig_th_I = 2 * np.pi * Delta * np.sqrt(np.concatenate(([0.0], np.cumsum(sig_tau_I ** 2))))
    sig_th_Q = 2 * np.pi * Delta * np.sqrt(np.concatenate(([0.0], np.cumsum(sig_tau_Q ** 2))))

    # truth: slice-weighted line (sharp mask on the fine grid) and exact phase
    HII_s, HQQ_s = _H_shift(HII), _H_shift(HQQ)

    def line(Hb, Hs, k):
        m = (freqs >= edges[k]) & (freqs < edges[k + 1])
        return np.sum(S_rrc * m * Hs * np.conj(Hb))
    tauI_t = np.array([-np.angle(line(HII, HII_s, k)) / (2 * np.pi * nu) for k in range(K)])
    tauQ_t = np.array([-np.angle(line(HQQ, HQQ_s, k)) / (2 * np.pi * nu) for k in range(K)])
    idx = [int(round(e / freqs[1])) for e in edges]
    thI_t = np.unwrap(np.angle(HII))[idx]; thI_t -= thI_t[0]
    thQ_t = np.unwrap(np.angle(HQQ))[idx]; thQ_t -= thQ_t[0]
    tau_ref = tauI_t[0]
    fc = edges[:-1] + Delta / 2
    pI = np.polyfit(fc, tau_I, 1, w=1 / sig_tau_I)
    pQ = np.polyfit(fc, tau_Q, 1, w=1 / sig_tau_Q)
    d_tau = tau_Q - tau_I
    d_tau_t = tauQ_t - tauI_t
    sig_d = np.sqrt(sig_tau_I ** 2 + sig_tau_Q ** 2)
    inner = slice(0, K - 1)                         # drop the roll-off slice
    w = 1 / sig_d[inner] ** 2
    skew = np.sum(w * d_tau[inner]) / np.sum(w)
    skew_sig = 1 / np.sqrt(np.sum(w))
    skew_t = np.mean(d_tau_t[inner])
    return dict(tau_I=tau_I, tau_Q=tau_Q, sig_tau_I=sig_tau_I, sig_tau_Q=sig_tau_Q,
                tauI_t=tauI_t, tauQ_t=tauQ_t, th_I=th_I, th_Q=th_Q, sig_th_I=sig_th_I,
                sig_th_Q=sig_th_Q, thI_t=thI_t, thQ_t=thQ_t, edges=edges, tau_ref=tau_ref,
                pI=pI, pQ=pQ, skew=skew, skew_sig=skew_sig, skew_t=skew_t, d_tau=d_tau,
                d_tau_t=d_tau_t, sig_d=sig_d)


def report(r):
    fc = edges[:-1] + Delta / 2
    fit_th = lambda p: -2 * np.pi * (p[0] * edges ** 2 / 2 + p[1] * edges)  # noqa: E731
    tau_ref = r["tau_ref"]
    print("\nper-slice group delay (ps), bulk delay removed:")
    print("  f(GHz)   tau_I meas   true    tau_Q meas   true    dtau meas  true   sigma")
    for k in range(K):
        print(f"  {fc[k] / 1e9:5.1f}  {(r['tau_I'][k] - tau_ref) * 1e12:9.2f} {(r['tauI_t'][k] - tau_ref) * 1e12:8.2f}"
              f"  {(r['tau_Q'][k] - tau_ref) * 1e12:9.2f} {(r['tauQ_t'][k] - tau_ref) * 1e12:8.2f}"
              f"  {r['d_tau'][k] * 1e12:8.2f} {r['d_tau_t'][k] * 1e12:6.2f}  {r['sig_d'][k] * 1e12:5.2f}")
    print(f"tau_g RMS err: I {np.std(r['tau_I'] - r['tauI_t']) * 1e12:.2f} ps, "
          f"Q {np.std(r['tau_Q'] - r['tauQ_t']) * 1e12:.2f} ps "
          f"(predicted sigma ~{np.mean(r['sig_tau_I']) * 1e12:.2f} ps)")
    eI = r["th_I"] - r["thI_t"]; eQ = r["th_Q"] - r["thQ_t"]
    print(f"accumulated phase: err at 50 GHz I {eI[-1]:+.3f} rad (sigma {r['sig_th_I'][-1]:.3f}), "
          f"Q {eQ[-1]:+.3f} rad (sigma {r['sig_th_Q'][-1]:.3f}); "
          f"max |err| over edges I {np.max(np.abs(eI)):.3f}, Q {np.max(np.abs(eQ)):.3f} rad")
    print(f"2-parameter fit:   err at 50 GHz I {fit_th(r['pI'])[-1] - r['thI_t'][-1]:+.3f} rad, "
          f"Q {fit_th(r['pQ'])[-1] - r['thQ_t'][-1]:+.3f} rad; curvature est "
          f"I {-r['pI'][0] * 2 * np.pi * F_EDGE ** 2 / 2:.3f} rad, "
          f"Q {-r['pQ'][0] * 2 * np.pi * F_EDGE ** 2 / 2:.3f} rad (true -6)")
    print(f"skew (interior slices, weighted): {r['skew'] * 1e12:+.3f} +- {r['skew_sig'] * 1e12:.3f} ps  "
          f"(true {r['skew_t'] * 1e12:.3f} ps, nominal {SKEW_PS} ps)")
    print(f"time to reach 0.1 ps skew at this dither depth: "
          f"{r['t_slice_ms'] * (r['skew_sig'] * 1e12 / 0.1) ** 2 * 2 * K / 1e3:.1f} s total")


def recompute(out, legacy_half_sample=False):
    d = dict(np.load(out + ".npz"))
    for k, v in d.items():
        if v.ndim == 0:
            d[k] = v.item()
    if legacy_half_sample:
        # files produced before the block-centre fix: the dither phase led by
        # half a sample (2.5 ps); rotate the lock-in outputs back (exact for a
        # single-tone dither, common to both branches and all slices).
        rot = np.exp(-2j * np.pi * nu * 0.5 / fs)
        d["B_I"] = d["B_I"] * rot
        d["B_Q"] = d["B_Q"] * rot
    if "sig_ph_I" not in d:                          # older file layout
        d["sig_ph_I"] = d["sig_tau_I"] * 2 * np.pi * nu
        d["sig_ph_Q"] = d["sig_tau_Q"] * 2 * np.pi * nu
    res = analyze(d["B_I"], d["B_Q"], d["sig_ph_I"], d["sig_ph_Q"])
    for k in ("spec", "eps", "t_slice_ms", "frac_db", "B_I", "B_Q", "sig_ph_I", "sig_ph_Q"):
        res[k] = d[k]
    np.savez(out + ".npz", **res)
    report(res)
    make_figure(out)


def make_figure(out):
    d = dict(np.load(out + ".npz"))
    for k, v in d.items():
        if v.ndim == 0:
            d[k] = v.item()
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    edges = d["edges"]; Delta = edges[1] - edges[0]
    fc = (edges[:-1] + Delta / 2) / 1e9
    eg = edges / 1e9
    lin = 2 * np.pi * edges * d["tau_ref"]
    fit_th = lambda p: -2 * np.pi * (p[0] * edges ** 2 / 2 + p[1] * edges)  # noqa: E731

    fig, ax = plt.subplots(2, 2, figsize=(13, 9))
    f_adc = np.fft.rfftfreq(Nd, 1 / fs_adc) / 1e6
    ax[0, 0].semilogy(f_adc, d["spec"] / d["spec"].max(), "r-")
    ax[0, 0].axvline(nu / 1e6, color="b", ls=":", label="$\\nu$ = 90 MHz")
    ax[0, 0].set_xlabel("ADC frequency (MHz)"); ax[0, 0].set_ylabel("PSD (norm.)")
    ax[0, 0].set_title("ADC (200 MS/s) spectrum, average over all records")
    ax[0, 0].legend(fontsize=8); ax[0, 0].grid(alpha=0.3)

    tr = d["tau_ref"] * 1e12
    ax[0, 1].plot(fc, d["tauI_t"] * 1e12 - tr, "k-", label="true $\\tau_{g,I}$")
    ax[0, 1].errorbar(fc, d["tau_I"] * 1e12 - tr, yerr=d["sig_tau_I"] * 1e12, fmt="ro",
                      ms=4, capsize=3, label="measured $\\tau_{g,I}$")
    ax[0, 1].plot(fc, d["tauQ_t"] * 1e12 - tr, "b-", label="true $\\tau_{g,Q}$")
    ax[0, 1].errorbar(fc, d["tau_Q"] * 1e12 - tr, yerr=d["sig_tau_Q"] * 1e12, fmt="g^",
                      ms=4, capsize=3, label="measured $\\tau_{g,Q}$")
    ax[0, 1].set_xlabel("slice centre (GHz)"); ax[0, 1].set_ylabel("group delay (ps), bulk removed")
    ax[0, 1].set_title(f"Per-slice group delay, $\\epsilon_s$={d['eps']}, "
                       f"{d['t_slice_ms']:.0f} ms per slice per branch")
    ax[0, 1].legend(fontsize=8); ax[0, 1].grid(alpha=0.3)

    ax[1, 0].plot(eg, d["thI_t"] + lin, "k-", lw=2, label="true $\\theta_I$")
    ax[1, 0].errorbar(eg, d["th_I"] + lin, yerr=d["sig_th_I"], fmt="ro", ms=4, capsize=3,
                      label="accumulated slice by slice")
    ax[1, 0].plot(eg, fit_th(d["pI"]) + lin, "r--", label="quadratic model fit")
    ax[1, 0].plot(eg, d["thQ_t"] + lin, "b-", lw=2, label="true $\\theta_Q$")
    ax[1, 0].errorbar(eg, d["th_Q"] + lin, yerr=d["sig_th_Q"], fmt="g^", ms=4, capsize=3,
                      label="accumulated")
    ax[1, 0].plot(eg, fit_th(d["pQ"]) + lin, "g--", label="quadratic model fit")
    ax[1, 0].set_xlabel("frequency (GHz)"); ax[1, 0].set_ylabel("phase (rad), bulk delay removed")
    ax[1, 0].set_title("Phase response: quadratic $-6(f/50\\,\\mathrm{GHz})^2$ rad")
    ax[1, 0].legend(fontsize=8); ax[1, 0].grid(alpha=0.3)

    ax[1, 1].plot(fc, d["d_tau_t"] * 1e12, "k-", label="true $\\tau_{g,Q}-\\tau_{g,I}$")
    ax[1, 1].errorbar(fc, d["d_tau"] * 1e12, yerr=d["sig_d"] * 1e12, fmt="ro", ms=4, capsize=3,
                      label="measured per slice")
    ax[1, 1].axhline(d["skew"] * 1e12, color="r", ls="--",
                     label=f"weighted mean {d['skew'] * 1e12:.2f}$\\pm${d['skew_sig'] * 1e12:.2f} ps")
    ax[1, 1].set_xlabel("slice centre (GHz)"); ax[1, 1].set_ylabel("$\\Delta\\tau$ (ps)")
    ax[1, 1].set_title(f"I/Q skew (nominal {SKEW_PS} ps)")
    ax[1, 1].legend(fontsize=8); ax[1, 1].grid(alpha=0.3)

    fig.suptitle("Dither via 720-point TX block FFT (block gain $1+\\epsilon\\cos 2\\pi\\nu t_b$ on 18-bin slices), "
                 f"$\\nu$=90 MHz, PD 100 MHz, ADC 200 MS/s\nlive 16QAM 100 GBaud, fresh data every record, "
                 f"no cancellation; dither power {d['frac_db']:.1f} dB re data", fontsize=11)
    fig.tight_layout()
    fig.savefig(out + ".png", dpi=140)
    print("figure:", out + ".png")


if __name__ == "__main__":
    main()
